### ISSUE TITLE
Documentation doesn't mention loading countries

### ISSUE THREAD

**Issue by JonTheNiceGuy** [GetTogetherComm/GetTogether#10]
I *think* from poking around in the code, I'd need to:

```
wget http://download.geonames.org/export/dump/countryInfo.txt
./env/bin/python manage.py load_countries countryInfo.txt
```

Without doing this, I can't create a team.

I think I might also need to add cities, but following similar steps for the unpacked cities1000.zip didn't do anything :(

**Comment by mhall119** [comment]
Ah, thanks, I forgot to add that, I'll update it to show all the specific files I downloaded and tested it on
