### ISSUE TITLE
Optionally enable/disable talk proposals

### ISSUE THREAD

**Issue by cassidyjames** [GetTogetherComm/GetTogether#109]
I am investigating using GetTogether for a weekly meetup. However, the format of the meetup doesn't really lend itself to having presentations. Would it make sense for that to be a per-event toggle to allow or disallow proposals?

**Comment by craigmaloney** [comment]
This would be excellent as not all of my meetings require talk proposals.

**Comment by mhall119** [comment]
On the Event Details for now you can enable/disable having presentations (and also photos or comments)

**Comment by cassidyjames** [comment]
Thanks @mhall119!
