### ISSUE TITLE
Currently, login needs to be via /admin and not using /

### ISSUE THREAD

**Issue by JonTheNiceGuy** [GetTogetherComm/GetTogether#11]
One of these options should be available:

1) "Do we have auth strings for Google/Twitter/Facebook/Github? Show their OAUTH flags. If not, login with /admin creds"
2) Follow the Sandstorm.io route - "Github/Google are fine auth systems. If not, we'll email you a sign-in URL. In all cases, you can run an admin command to get an admin URL"
3) Go with the Mozilla auth route - "We never store auth creds about you - but we expect a working email server. Put in your email address, we'll email you a sign-in URL"

I am aware this is very early code :) However, having the OAUTH flags at the outset means there's an expectation these will work - which isn't the case, unless there's a localhost-auth-route that we could be using... and I don't think that's there yet.

**Comment by mhall119** [comment]
I've tested the Github login with actual Github auth tokens, but those aren't checked into git. The idea is to support them, but require each deployed instance to get their own auth token specific to their instance name.

The current auth setup was thrown together as the bare minimum to get started, it still needs a lot of work, to be configurable depending on each deployment's needs. I'll look into Sandstorm and what Mozilla does, as you suggested. Any other advice or assistance you can give here would be most appreciated.

**Comment by JonTheNiceGuy** [comment]
I quite like Sandstorm's onboarding process. At the end of the installer, you get a URL to access, and you set up all the rest of your auth from in there. You can also add them as part of the installer script for automation.

**Comment by mhall119** [comment]
As a quick measure I've gone with option 1, it'll show Google and/or Github login if you have the appropriate keys in your local_settings.py, and it will also show you "Local" login (via the admin) if DEBUG=True for local development
