### ISSUE TITLE
Search event feature while being logged in

### ISSUE THREAD

**Issue by blankoworld** [GetTogetherComm/GetTogether#113]
#38 add an event search feature, but it seems to not appear when we are log in.

Is that an expected behaviour?

How can I search for some events?

**Comment by mhall119** [comment]
The original issue referred to searching for events by city & distance, which you can do from the homepage (logged in or not).

**Comment by blankoworld** [comment]
It seems that I didn't finished the initial account setup. Which didn't display homepage and so search bar.

Sorry for that, we can close this ticket ;)
