### ISSUE TITLE
Serve FontAwesome from local static files rather than remote CDN

### ISSUE THREAD

**Issue by BobJonkman** [GetTogetherComm/GetTogether#115]
Some characters are not displaying in my web browser (IceCat 52.6.0), which is secured to disallow third-party scripts, fonts, &c. (see attached image)

Most widgets on the screen ("Edit Team", "Manage Members") have text, so the absence of extended characters is benign, but the "iCal" link is unrecognizable without text; I didn't even know there was an iCal option available!

Request: Add plain text to all links, don't rely only on extended characters.

Of course, I would prefer that the WebUI doesn't use any extended characters at all, but that may be aesthetically displeasing :-)

--Bob.
![screenshot at 2018-08-24 13 12 50](https://user-images.githubusercontent.com/5558697/44600097-3b885400-a7a6-11e8-9b5e-0cd1fbc2ad3e.png)

**Comment by mhall119** [comment]
I'm using the freely available FontAwesome fonts for these. Currently it's loading the css for that from FontAwesome's CDN, which is why it was being blocked. I'll add a static version into GetTogether's codebase.

**Comment by BobJonkman** [comment]
That should do it!

Thanx!
--Bob.
