### ISSUE TITLE
docker-compose / docker dont work when creating the superuser

### ISSUE THREAD

**Issue by albjeremias** [GetTogetherComm/GetTogether#117]
Hi,
I am following the procedure on the README.md ... So heres my proceeding:

```
$ git clone urrepo
$ docker-compose up
```
I can visit http://localhost:8000 it gives many errors.. but it works... but when i try to create the super user with:
` $ docker-compose exec get_together python3 manage.py createsuperuser `
 i get the following error:
```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

**Comment by mhall119** [comment]
Ah, it's not calling the new virtualenv in the container, try this:
`docker-compose exec get_together /home/python/venv/bin/python manage.py createsuperuser`
