### ISSUE TITLE
It's only possible to access the site using 127.0.0.1/localhost

### ISSUE THREAD

**Issue by JonTheNiceGuy** [GetTogetherComm/GetTogether#12]
My standard development practice is to deploy to a vagrant host and then access it using a private network (it's a weird quirk - I know that 😦, but I like isolating my development environments), however, this means I got:

```
DisallowedHost at /

Invalid HTTP_HOST header: '192.0.2.100:8000'. You may need to add '192.0.2.100' to ALLOWED_HOSTS.
```

From reading the code, I *assume* I should create /get_together/local_settings.py which has `ALLOWED_HOSTS = [ '0.0.0.0/0' ]` or `ALLOWED_HOSTS = [ '192.0.2.100' ]` but... I'm not really a Django user, so I don't know the convention here.

**Comment by mhall119** [comment]
For Docker we're going to use environment variables passed through to the container to configure things like this, would what work for Vagrant too?

**Comment by JonTheNiceGuy** [comment]
Yes, we can. There are two options
1. we can use the env line like below
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8000, host: 8080
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y python3 python3-pip
  SHELL
  config.vm.provision "shell",
    env: {"DEBUG" => "#{ENV['DEBUG']}"},
    run: "always",
    inline: <<-SHELL
      cd /vagrant
      pip3 install -r requirements.txt
      python3 manage.py migrate
      python3 manage.py runserver 0.0.0.0:8000
    SHELL
end
```

2. We could create an env file to load:
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8000, host: 8080
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y python3 python3-pip
  SHELL
  config.vm.provision "shell",
    run: "always",
    inline: <<-SHELL
      cd /vagrant
      source envfile
      pip3 install -r requirements.txt
      python3 manage.py migrate
      python3 manage.py runserver 0.0.0.0:8000
    SHELL
end
```

While both of these examples would work, they're not perfect  (I knocked them up in a couple of minutes) :)

**Comment by mhall119** [comment]
I've added an environ_settings.py that will let you set certain config values from your environment variables. You can use it either by adding --settings=get_together.environ_settings to the end of your manage.py command, or by setting DJANGO_SETTINGS_MODULE=get_together.environ_settings in your environment.

And example command would be:
`DJANGO_SETTINGS_MODULE='get_together.environ_settings' DATABASE_URL='sqlite:////path/to/your/db.sqlite3' SECRET_KEY='foobar' python3 manage.py runserver 0.0.0.0:8000`

DATABASE_URL follows [this project's spec](https://github.com/kennethreitz/dj-database-url) and requires pip installing dj-database-url (which is now in the requirements.txt). 

I hope this does what you need it to do. If not, let me know what's missing.
