### ISSUE TITLE
Make all display strings translatable

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#122]

**Comment by SvetlanaTkachenko** [comment]
Hi,

Thanks for this request.

I would be willing to translate to Russian. 

Here is a nice software for translator portal:
https://weblate.org/en/
I think they may be willing to assist with installation and setup if needed.

**Comment by mhall119** [comment]
Hi @SvetlanaTkachenko, thanks for offering to help! We're already setup in [Transifex](https://www.transifex.com/gettogether/gettogether-website-1/dashboard/) but I'm open to changing platforms of there's a benefit to switching

**Comment by mhall119** [comment]
@SvetlanaTkachenko translations can be added to https://www.transifex.com/gettogether/gettogether-website/dashboard/ now.

I'm still open to moving to weblate if it gives us some better features or access
