### ISSUE TITLE
Firefox complains site is not secure

### ISSUE THREAD

**Issue by popey** [GetTogetherComm/GetTogether#135]
Looks like https://gettogether.community is serving via https but the gravatar in the top right corner is http, so firefox complains that there's https and http mixed on the page.

![image](https://user-images.githubusercontent.com/1841272/48856019-40f93880-edad-11e8-8d5b-30e56d9e29ec.png)

Perhaps you could load them from gravatar over https?

**Comment by mhall119** [comment]
Is Firefox happy now?

**Comment by popey** [comment]
Yes! Firefox is happy again! Thanks!
