### ISSUE TITLE
OperationalError no such table when running gettogether locally

### ISSUE THREAD

**Issue by renatolond** [GetTogetherComm/GetTogether#157]
Hi!
I'm trying to run gettogether locally and both using docker or running it manually in 0.9.0, I get the following error when I try to login:

```
OperationalError
no such table: main.auth_user__old
/home/renatocerqueira/src/GetTogether/env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 303
/home/renatocerqueira/src/GetTogether/env/bin/python
3.7.2
['/home/renatocerqueira/src/GetTogether',  '/home/renatocerqueira/src/GetTogether/env/lib/python37.zip',  '/home/renatocerqueira/src/GetTogether/env/lib/python3.7',  '/home/renatocerqueira/src/GetTogether/env/lib/python3.7/lib-dynload',  '/usr/lib64/python3.7',  '/usr/lib/python3.7',  '/home/renatocerqueira/src/GetTogether/env/lib/python3.7/site-packages',  '/home/renatocerqueira/src/GetTogether']
Qui, 7 Fev 2019 12:25:04 +0000
```

The traceback can be seen here: http://dpaste.com/2KE467N

**Comment by georgedorn** [comment]
This confusing error is due to a change in sqlite3 that breaks compatibility with Django.  See https://code.djangoproject.com/ticket/29182 which suggests it will be fixed in Django 2.2.

You can work around the problem by downgrading sqlite3 to 3.25, or running the code in comment 16 (I'm unclear if you need to do it just once for the db, or every time python starts, perhaps in settings.py).

**Comment by renatolond** [comment]
Hey, sorry, haven't had time to try the patch yet, as soon as I do I'll let you know, thanks for looking into it!

**Comment by renatolond** [comment]
I've updated the django in requirements to 2.0.12, which contains https://github.com/django/django/commit/53b17d4734f06372b66e3ac4db7a1740c503b330 (I think I could've gone with 2.0.10), removed the database and recreated the file and it works!
Just updating django without touching the database didn't seem to fix the issue, even re-running migrate, I'm not quite sure why :thinking:
