### ISSUE TITLE
Add remove image feature to meetup page

### ISSUE THREAD

**Issue by hollodotme** [GetTogetherComm/GetTogether#169]
## Expected behavior

The event host should be able to remove uploaded images from an event.

Depending on the underlying role management (which I don't know about), it could also be a good idea that the uploader (person) of an image is additionally able to remove it.

## Actual behavior

Currently it is not possible to remove or replace an image once it was uploaded for an event. Only new images can be uploaded.

Example: https://gettogether.community/events/910/meetup-iii-2019-oss-contributing-and-event-sourced-cms/

I am not able to remove the first placeholder image.

/cc @bcremer

**Comment by mhall119** [comment]
This ability has been added to the site

**Comment by hollodotme** [comment]
Wow! That was fast. Thank you very much! 👌
