### ISSUE TITLE
can't complete acount setup

### ISSUE THREAD

**Issue by mimmi20** [GetTogetherComm/GetTogether#175]
I created a account today (via github). Since then, I get the message to complete the acount setup.

![image](https://user-images.githubusercontent.com/1120192/55981192-8bb11980-5c96-11e9-91c3-371ec63e36bb.png)

When I click on the [link](https://gettogether.community/about/profile/+confirm_profile), I get an error page.

![image](https://user-images.githubusercontent.com/1120192/55981351-bac78b00-5c96-11e9-91a3-96dfc1229f91.png)

And the link changes to [this](https://gettogether.community/about/profile/profile/+confirm_profile) and to [this](https://gettogether.community/about/profile/profile/profile/+confirm_profile) after the next click.

Browser: Opera 58

**Comment by pixelbrackets** [comment]
The link is relative, therefore it will fail on all subpages. And create a chain like described above.

On https://gettogether.community/events/1048/meetup-iv-2019-mutation-testing/ it will create https://gettogether.community/events/1048/meetup-iv-2019-mutation-testing/profile/+confirm_profile on there https://gettogether.community/events/1048/meetup-iv-2019-mutation-testing/profile/profile//+confirm_profile and so on…

Instead it should point to https://gettogether.community/profile/+confirm_profile

To do so the variable »SETUP_URL« needs to be changed imho.

**Comment by pixelbrackets** [comment]
Fixed with #178

**Comment by mimmi20** [comment]
Thanks
