### ISSUE TITLE
Add Mastodon Sharing Link 

### ISSUE THREAD

**Issue by craigmaloney** [GetTogetherComm/GetTogether#191]
Would like to have a way to share meetings via Mastodon. This might be tricky because you'd need to have a way to set the server that the user would post to.

**Comment by mhall119** [comment]
Yeah, I looked into this, and the fact that it would have to prompt the user to enter their instance hostname makes it easier to just copy/paste the URL into a Mastodon client. I hope to soon add enough ActivityPub that Mastodon users can follow a team, and see new events as they are created

**Comment by mhall119** [comment]
I'm tempted to mark this as "won't fix" for the above reason, but if a better solution is possible I'd like to hear about it

**Comment by craigmaloney** [comment]
We can close it for now. I think the appropriate way to share on Mastodon would be via ActivityPub, and it would be best to focus on supporting that rather than the crude hacks of yester-year. :wink:
