### ISSUE TITLE
Document versioning conventions

### ISSUE THREAD

**Issue by WillPlatnick** [GetTogetherComm/GetTogether#2]
What is going to be our convention for versioning software?

Some Options:
Semantic Versioning - https://semver.org/
Calendar Versioning - https://calver.org/

**Comment by mhall119** [comment]
I'd prefer semantic, personally. It lets us establish compatibility via major versioning, and I don't think we'll be sticking to a rigid release schedule that would benefit from calendar versioning

**Comment by WillPlatnick** [comment]
Sounds fine to me. We should probably have some something in the docs committing to that.

**Comment by mhall119** [comment]
You say "in the docs" as if there's more than just a README at this point :)

But yes, we should start docs and this should be in them.

**Comment by WillPlatnick** [comment]
README it is

**Comment by bheesham** [comment]
What is the version of the software? There's no `__version__` variable defined in the `get_together` module.

**Comment by mhall119** [comment]
There hasn't been any official version or release yet, so 0.1.0 seems right to me
