### ISSUE TITLE
Gitter is mentioned as primary chat platform for contribution

### ISSUE THREAD

**Issue by craigmaloney** [GetTogetherComm/GetTogether#202]
On the main page of Github (the README.md file) it mentions Gitter as the primary area for chatting with developers.

Now, I'm not saying this is a bug (I prefer Gitter) but there's no link to the Telegram room that is where the conversations are happening.

Perhaps this link should be changed? (Or, alternately, a platform like Gitter should be used instead of Telegram, but that's just my silly opinion. :) )

**Comment by v4ld3rr4m4** [comment]
Telegram is mentioned  however the group not appear in search

**Comment by mhall119** [comment]
I'm not sure why, it's set to be visible in Telegram.

Here's the join link: https://t.me/joinchat/AlruIk5yiQizaJ0YtYehzA
