### ISSUE TITLE
Incompatible with debian 10 "buster"? (with a potential fix)

### ISSUE THREAD

**Issue by 7usr7local** [GetTogetherComm/GetTogether#204]
_I could have called this "Incompatible with Python 3.7" but as I had troubles using Python 3.5 on debian 10, I called it "Incompatible with debian 10"._

After upgrading my server running GetTogether from debian 9 to debian 10 apache stopped working - i.e. it was running, but didn't answer any http/s request - neither GetTogether nor other vhosts (running on the same IP)
There had been a lot of errors in apaches default error.log saying

```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

I tried to recreate the virtualenv directory GetTogther was running in. As debian 10'd default python version is 3.7, I tried with --python=python3.5 - no luck.

Next try was to create the virtualenv environment using --python=python3 as written in the README, picking Python 3.7 by debian's default.

This time the pip install step failed with Pillow complaining about missing zlib. I realized, requirements.txt referred to Pillow 5.0.0 which is according to [https://pillow.readthedocs.io/en/latest/installation.html](https://pillow.readthedocs.io/en/latest/installation.html) not compatible with Python 3.7, so I just hacked requirements.txt to refer to Pillow 5.2.0 and all seems to run fine now.

Any comments on the first error or on my hacking requirements.txt would be appreciated.
If this is a reasonable solution, my findings might be helpful for other people too.

**Comment by mhall119** [comment]
Upgrading Pillow to 5.2.0 is easy to do, as long as all the tests pass.

As far as incompatibility with 'encodings' and Python 3.7, we'd need to investigate more, as there may be code in other dependencies that use it too.

To start with, send a PR with the Pillow upgrade and we can get that merged.

**Comment by 7usr7local** [comment]
Hi @mhall119,
thanks for your comment. I am not sure how to proceed ... I could provide (possibly) a PR with just the requirements.txt modified. But I am not sure how to make sure that "all the tests pass".  I am more an admin then a dev here.

**Comment by mhall119** [comment]
After you update the requirements.txt, follow the instructions in the README.md to get a local development environment up and running. Then run `./env/bin/python manage.py test` to run the test suite. If all tests pass, then your change is good to go and you can send it as a PR

**Comment by 7usr7local** [comment]
I am afraid, there is still an information gap ... I started with gettogether-0.9.0.tar.gz, not with a git clone. Now I encounter

```
$ ./env/bin/pre-commit install
bash: ./env/bin/pre-commit: No such file or directory
$ 
```

**Comment by mhall119** [comment]
The tarball is pretty old, we've been using more of a rolling-release development model since then. I would recommend trying again with a git clone of `master` instead.

**Comment by bremensaki** [comment]
I did a full installation of master from scratch on Debian 10 a couple of days ago, and encountered no issues with Python 3.7 compatibility. Listed versions of everything in requirements.txt installed without issue.

**Comment by 7usr7local** [comment]
I opened this to verify that increasing Pillow from 5.0 to 5.2 in requirements.txt is a viable solution. As it is 6.2 in master now, I consider the question answered :wink:
