### ISSUE TITLE
Event scheduled for tonight is showing in the past

### ISSUE THREAD

**Issue by craigmaloney** [GetTogetherComm/GetTogether#209]
This event is showing as having already happened:

https://gettogether.community/events/2228/monthly-meeting/

Not sure what happened?

**Comment by mhall119** [comment]
Midnight on Oct 8th was 12:00am this morning, not 12:00am tomorrow morning.

**Comment by mhall119** [comment]
That is peculiar, it seems past events in the series were created properly....

**Comment by craigmaloney** [comment]
Will keep an eye on this. Wonder if something happened in the series
creation.

* Michael Hall (notifications@github.com) wrote:
> That is peculiar, it seems past events in the series were created properly....
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GetTogetherComm/GetTogether/issues/209#issuecomment-539627720
--
  Craig Maloney  (craig@decafbad.net)  http://decafbad.net

**Comment by mhall119** [comment]
I'm closing this, but please re-open if it happens again

**Comment by craigmaloney** [comment]
No worries. Thanks for looking into it.
