### ISSUE TITLE
It's not clear how to properly finish setting up your profile

### ISSUE THREAD

**Issue by RandyWalker** [GetTogetherComm/GetTogether#211]
I signed up via Twitter, verified my email address, and completed my profile. Still, each page shows the

Click here to finish your account setup.

message that takes me to https://gettogether.community/profile/+confirm_profile

Clicking Continue at the bottom of the page doesn’t make the message go away.

**Comment by svdo** [comment]
Just saying 'me too', but in my case it's a "standalone" account, not a login using another platform.

**Comment by tsdgeos** [comment]
Yes, i had the same problem, it's not clear, i think the problem is that it should bring you to the "pick categories" page not to the "set your name and email" page

**Comment by bkil** [comment]
Only a few people in our team managed to finish these despite the fact that everyone is a techie. I think the UX puzzle is not very user friendly.

**Comment by craigmaloney** [comment]
@mhall119 Should we let users know that they can now complete their profiles, or is there a way to do that automatically? I know a few folks that are still incomplete.

**Comment by mhall119** [comment]
If they're still getting the banner at the top of the page, they can follow the link and now it should be more obvious how to complete it

**Comment by craigmaloney** [comment]
OK, I'll check with them. Thanks!
