### ISSUE TITLE
Map doesn't update new events

### ISSUE THREAD

**Issue by eabedrapo** [GetTogetherComm/GetTogether#232]
**Actual results:** the map at the home page doesn't seem updated with the event I created last night.

**Expected results:** All new events should be displayed in the map at the location of the venue.

**Steps to reproduce:**
1. Create a new event in a location that doesn't have any previous pin.
2. Return to the home page to get the map displayed.
3. Check if the new event has been added to the map. Zoom in the event area if needed.

**Comment by mhall119** [comment]
This should update immediately. What is the event that isn't showing?

**Comment by eabedrapo** [comment]
I’m actually heading over there now so I’m answering via email (don’t use
GitHub on mobile).

It’s the Open Source Chicago’a Jam... it’s actually displayed at the end of
the page as it seems the events aren’t sorted by their occurrence date on
the home page...

**Comment by mhall119** [comment]
Ah, it's not showing because it thinks the event is over, it's end time is 6am today. I've  created #235 to try and prevent this from happening in the future, and for now I've manually changed your event's end time to be 6pm rather than 6am, assuming that was the intended value.

I also noticed that the longitude and latitude values were swapped for the venue. Did you enter these yourself or did you use the Google map to select the location?

**Comment by eabedrapo** [comment]
It was showing 2pm for me las night but not showing anyway... I also
noticed some weird issues with timing, but I need to test more to raise the
issue.

**Comment by eabedrapo** [comment]
Sorry @mhall119 I just realized I didn't answer your question regarding Lat/Long of my event: I entered them myself as I didn't see how I should do it via GMaps... that said when I created other events I did noticed that the form shows Longitude before Latitude, so maybe I didn't notice I have switched them as for me Latitude always come before than Longitude... but maybe it's just me.

By the way, can't we just use an address autopopulated via some API (Gmaps, OSM or similar?

The way it's implemented today is prone to errors from the end-user and the instructions to pre-populate location data in the contributor's environment (in the [README.md]) sound a little weird to me.

Do you want me to create an issue to cover that?

Regarding this particular issue, I think the problem was that I was able to save the event details with end before start time, but not sure... after you fixed the end time it showed fine in the map, so I'm going to close this one.

**Comment by mhall119** [comment]
If you click on a location on the map it will auto-populate the place fields for you. Perhaps we just need  to make this more intuitive?

**Comment by eabedrapo** [comment]
I agree!

In many websites when an address is requested they have a typeahead that uses Google Map's API or similar... but as far as I know GMaps has a limit for free calls to their API, so maybe we could check if OpenStreetMap offers something more sustainable for a project like this.

I didn't see any issues around this requirement, so if you want I can raise it to start investigating what we can do to make the address setup more user friendly/intuitive for everybody.

**Comment by mhall119** [comment]
Yes, please raise the issue and let us know what you find. If the Google
API limit is reasonable we could still use that for place lookups, as they
don't happen that frequently.
