### ISSUE TITLE
Team page title text prefix "Welcome to" is not wanted. 

### ISSUE THREAD

**Issue by ianp5a** [GetTogetherComm/GetTogether#239]
Requirement: Remove the "Welcome to" prefix on the main page of a team. Or add customisation to edit it.

Reason: If the Page is about "Team A".The title is best "Team A" The prefixing "Welcome to"  is unnecessary and takes up space. It is reminiscent of 90's websites that was dropped for good reason.

Papercut type refinement

**Comment by Oxymora** [comment]
I will do it

**Comment by ianp5a** [comment]
Test Good. Thanks.
