### ISSUE TITLE
Removing sponsors doesn't seem to work

### ISSUE THREAD

**Issue by tsdgeos** [GetTogetherComm/GetTogether#255]
I've been able to add sponsors to https://gettogether.community/events/3476/why-snaps/ just fine, but then i wanted to remove one (which i don't anymore, i thought the logo would look wrong) and pressed the Delete button and nothing happened.

**Comment by mhall119** [comment]
The "Remove" button is a toggle that uses Javascript. Do you happen to have Javascript disabled?

**Comment by tsdgeos** [comment]
No, i do not have javascript disabled.

Here what happens when i press the three buttons

![imatge](https://user-images.githubusercontent.com/9051674/70650281-1b0c3380-1c4f-11ea-85bb-2c9be615941b.png)

**Comment by mhall119** [comment]
Ah ha! Thanks for the screenshot, it looks like it's a bug introduced by translations. The Javascript checks the text of the button to decide what action to perform...but the check only checks for English.

The Javascript should be updated to not depend on the button text, but rather on a parameter passed to it.

**Comment by mhall119** [comment]
While you wait for this to get fixed, would you like me to remove OpenSUSE from your list of sponsors?

**Comment by tsdgeos** [comment]
oh no, the list of sponsors is correct
