### ISSUE TITLE
Allow user to view and edit profiles

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#27]
Allow people to view profiles of another user, and edit their own profiles

**Comment by bheesham** [comment]
What's in `master` allows people to edit their profiles. I'll be working on allowing people to view other's profiles.

**Comment by bheesham** [comment]
It may be a good idea (maybe as a milestone for 0.4.0) to give users the ability to set who is allowed to view certain information on their profile (email).

**Comment by mhall119** [comment]
Thanks for the addition!
