### ISSUE TITLE
Internal Server Error when click on Events or Teams

### ISSUE THREAD

**Issue by TomThats** [GetTogetherComm/GetTogether#279]
Tested with: 
Version 81.0.4044.138 (Offizieller Build) (64-Bit) on Win 10
same result with/without incognito mode

**Steps to reproduce:**

**1.** go to gettogether.community
**2.** click on "Events" in top left corner
**3.** redirecting to https://gettogether.community/events/all/
**4.** receive 500 Internal Server Error

**or:** 
**2.** click on "Teams" in top left corner
**3.** redirecting to https://gettogether.community/teams/all/

**Result:**
![image](https://user-images.githubusercontent.com/3465653/82882448-5c647700-9f41-11ea-8b24-01395d47844e.png)

**Comment by christophfriedrich** [comment]
I also get a 500 error when trying to see teams in my city.

Steps to reproduce:
1. go to gettogether.community
2. type "Münster" into the *City* box, select "Münster, North-Rhine Westphalia, Germany", click *Search*
3. this redirects to https://gettogether.community/?name=&city=72109&distance=100
4. see 500 error

**Comment by mhall119** [comment]
This turned out to be caused by an upload image that was too large for the thumbnailer to process, causing it to crash and taking Django along with it. I've resized and re-uploaded the image and now it's working fine.
