### ISSUE TITLE
Setup Travis CI Account

### ISSUE THREAD

**Issue by WillPlatnick** [GetTogetherComm/GetTogether#3]
We will need a CI/CD system to automatically build, test and release the software.

Travis is a great option because it's powerful and free for open source projects.

Unless anybody has a really good reason not to use Travis, let's go for it.

**Comment by mhall119** [comment]
No objections from me, I think Travis is the best option too

**Comment by mhall119** [comment]
I have a Travis account setup now, and a .travis.yml file in the repo, but the Travis job is segfaulting when running the django tests. I can't reproduce this on my local machine, even using a clean virtualenv. Can you me with this?

https://travis-ci.org/GetTogetherComm/GetTogether/jobs/471128356
