### ISSUE TITLE
Locations no longer working on the main site (gettogether.community)

### ISSUE THREAD

**Issue by craigmaloney** [GetTogetherComm/GetTogether#302]
Steps to reproduce:

Head to the gettogether.community site

What you'll see:

"We were unable to determine your location. Use the search field above to enter your city."

What we should see:

Events for the location.

Hoping it's a simple fix. Thanks!

**Comment by mhall119** [comment]
The fix was to pay for the IPStack geoip lookup service because GetTogether was hitting the free-tier API usage limit
