### ISSUE TITLE
Enable translations

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#32]
Configure the process for exporting .pot files and importing .po files. Make sure any hard-coded display strings are wrapped in the appropriate translation tags/functions

**Comment by mhall119** [comment]
Translations are enabled now in Transifex. Still need to review all strings and also document the process for importing translations, but those can be other tasks

**Comment by DinizCabreira** [comment]
Apologies if I am necroposting here, but I wanted to contribute a portuguese translation (perhaps a spanish one too). How can I help?
