### ISSUE TITLE
Send email reminders for upcoming events

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#35]
When a user marks themselves as wanting to attend an event, give them the option to receive reminder emails some period of time before the event.

**Comment by mhall119** [comment]
Thanks @bheesham!
It will need to be triggered by cron, so check out https://github.com/GetTogetherComm/GetTogether/blob/master/get_together/management/commands/send_email_confirmation_reminder.py for an example of how to approach it.

**Comment by mhall119** [comment]
You'll need to create two new templates (txt and html) for the message, and pass in the event object as well as the target user object.

**Comment by bheesham** [comment]
Excellent. Thanks for the pointers!

**Comment by mhall119** [comment]
@bheesham have you started on this yet? If not I might work on it tonight to try and finish off the 0.3.0 milestone tasks

**Comment by bheesham** [comment]
Working on it now. Sorry about the delay, I got distracted on the weekend.
