### ISSUE TITLE
Can't handle non-square profile pictures

### ISSUE THREAD

**Issue by NeoTheThird** [GetTogetherComm/GetTogether#48]
On the edit profile page, a URL for a profile pic can be entered freely (which is pretty cool), but the website can not handle it elegantly. If I set [a picture with a non-square aspect ratio](https://ubports.com/web/image/781), it's shown in unexpected ways:

![bildschirmfoto zu 2018-03-13 23-08-48](https://user-images.githubusercontent.com/12068939/37372592-8688b01c-2713-11e8-81eb-117ccee26164.png)
![bildschirmfoto zu 2018-03-13 23-08-32](https://user-images.githubusercontent.com/12068939/37372593-86aad03e-2713-11e8-8eae-0cee014e8260.png)
![bildschirmfoto zu 2018-03-13 23-06-57](https://user-images.githubusercontent.com/12068939/37372594-86c99622-2713-11e8-94ed-fca98b06d351.png)

**Comment by mhall119** [comment]
This is fixed by virtue of switching to uploaded avatar images and auto-resizing and cropping them

**Comment by mhall119** [comment]
You'll need to upload a new avatar image for this to take effect on your profile

**Comment by NeoTheThird** [comment]
Thanks for fixing :+1:

Gotta admit i kinda grew to like it, though. Makes me feel special. An elliptical individual in this cruel circular world.
