### ISSUE TITLE
Enable searching for place names / allow for frequently used places

### ISSUE THREAD

**Issue by craigmaloney** [GetTogetherComm/GetTogether#49]
When creating a new event I wanted to be able to use the place that I had used for the previous event. Unfortunately that information wasn't available to me and I stalled while entering the new event.

Ideally this would either keep a table of the previously used places per team / event, or allow for searching for existing places / adding new places.

**Comment by mhall119** [comment]
Now you'll see previously used places on the map when choosing the location for a new event. Clicking on one of them will reuse that place.
