### ISSUE TITLE
Create account with a docker registry

### ISSUE THREAD

**Issue by WillPlatnick** [GetTogetherComm/GetTogether#5]
We need a place to publish our docker images. Some possible options:

Docker Hub
quay.io

My vote is for quay.io due to better auth controls and more advanced feature set.

**Comment by mhall119** [comment]
Does it have to be one or the other, or would there be a benefit to publishing in both?

**Comment by WillPlatnick** [comment]
IMHO, there's not a lot of benefits to publishing to multiple registries. It would make build pipelines a little bit more complex for not much in return.

**Comment by mhall119** [comment]
Account created on DockerHub and configured to auto-build imges
https://hub.docker.com/r/gettogethercomm/gettogether
