### ISSUE TITLE
Determine hosting provider

### ISSUE THREAD

**Issue by WillPlatnick** [GetTogetherComm/GetTogether#6]
We need a place to put this thing :)

My vote is for Google Container Engine (GKE), which is Google's Hosted Kubernetes solution. I think it's the right balance between getting us up and running quickly, cost effectiveness (especially since getting rid of the management fee), and looking to the future.

**Comment by mhall119** [comment]
How does GCE compare price wise to AWS or someone smaller like Linode, Digital Ocean or Rackspace?

**Comment by WillPlatnick** [comment]
As a rule, Google is almost always cheaper than AWS because they're trying to get market share and undercut AWS pricing as a general strategy.

https://cloud.google.com/compute/pricing

As things are getting built and we don't care quite as much about high availability, we could use one node, and scale up and out quickly and easily.

It's definitely different than just getting a single VM at Linode/DO and managing it by hand.

If we want to go to the Kubernetes route, I'd go with GKE.

If we don't want Kubernetes and just run this by hand, a cheap linode/do would be perfectly fine.
