### ISSUE TITLE
Fix Place map to use coordinates to center

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#69]
Currently the Place display page is using Google's place lookup API which uses only name and city, not coordinates, and it sometimes gets confused

**Comment by femilamptey** [comment]
@mhall119 Hey, I tried my hands on a solution.

**Comment by mhall119** [comment]
Thanks @femilamptey but it doesn't appear that this will work, trying that URL I get:

> The Google Maps API server rejected your request. Invalid request. Missing the 'q' parameter.

It appears that this API is only usable for looking up places by name.

**Comment by femilamptey** [comment]
Hey @mhall119 so I took another look and modified the src, hope it works this time. I haven’t been able to actually run it on my computer to check it out myself for some reasons, I apologise. Always happy to help though!
