### ISSUE TITLE
Build docker compose for easy development

### ISSUE THREAD

**Issue by WillPlatnick** [GetTogetherComm/GetTogether#7]
Build a docker compose file to allow for easy development.

I'm not a python dev, but I imagine there is something we can use that monitors the file system for changes and reloads the necessary django components.

**Comment by mhall119** [comment]
When running Django's built-in server for development testing, it will notice filesystem changes itself and reload the necessary components. In production, using WSGI, it would need to force it

**Comment by almereyda** [comment]
The pull request brings a development environment.

Would you also be interested in a production environment?

**Comment by mhall119** [comment]
I would be interested in a production build, but ideally that would have different containers for the app, the database, load balancers, caching proxiess, whatever.

**Comment by rikmendes** [comment]
Would be very interested also on a production build.. I want to try to then bring this docker build as Cloudron app (cloudron.io)
