### ISSUE TITLE
Add a local login option

### ISSUE THREAD

**Issue by BobJonkman** [GetTogetherComm/GetTogether#80]
Please add a local login option.

The only way to log in is with a Google, Facebook, Twitter or GitHub account. This prevents participation by people who don't have one of those accounts.

I prefer to use Free Software, in part to avoid surveillance companies like Google, Facebook, Twitter or GitHub; at the moment GetTogether doesn't meet that use case.

Thank you,
--Bob.

**Comment by mhall119** [comment]
This has been added as an option

**Comment by BobJonkman** [comment]
Thanx!

--Bob.
