### ISSUE TITLE
Host an event without team

### ISSUE THREAD

**Issue by burnoutberni** [GetTogetherComm/GetTogether#92]
First issue here, so first of all thanks for your efforts, I had a similar idea for a project and think it's really cool how far you've already come.

As a suggestion for me to use GetTogether, I would strongly prefer to be able to create events without creating a team. My use-case for this tool would be very similar to Facebook Events, where I regularly create small scale public events on my own without an organization or group in the background. I can understand if your focus is different (community-centric), but even then I think having to create a team first adds another layer of complexity that first-time users don't necessarily recognize from other platforms.

**Comment by mhall119** [comment]
If you regularly create events, is there a reason you don't want to create a team to group them all under? A "team" can be just one person (though you miss out on some benefits using it that way), but it makes it easy to see past and future events that are somehow associated with each other.

**Comment by polymerwitch** [comment]
I was thinking I wanted a feature like this as well. I like the idea of an individual being able to jump on the service and create an event. But after using gettogether a bit I see that Teams are an analog for meetup groups. It seems like this could be addressed with #56 by creating form that appears when a user belongs to no teams that adds a couple fields asking about how to publicly list who is hosting the event. A team could then be created and the new event connected to it in the same server request.

**Comment by mhall119** [comment]
Yes, I was thinking of much the same thing for #56, would that serve your need @burnoutberni?

**Comment by mhall119** [comment]
Having an Event object without a Team would require a lot of refactoring, because an event relies on information from it's team for a lot of things. How about if instead of having "no team" we create a private "personal" team that belongs to the user and isn't listed publicly anywhere? This could be tied in with implementing #46

**Comment by bheesham** [comment]
Nice, I like that idea.
