### ISSUE TITLE
Cross-Site Request Forgery vulnerability

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#96]
_Reported via email_

Joining a group is done through a request such as:

GET /team/75/+join/

This means that once you are connected another on the site, an attacker
can add make you join to a group or leave a group without your consent
and without you noticing by including a link to this URI:

<img src="https://gettogether.community/team/75/+join/">

I checked and visitinv this HTML page from another web site actually
makes you join the team.

The same goes for joining events:

<img src="https://gettogether.community/events/70/+attend/?response=yes">

You should really use POST (and CSRF tokens) for these requests as well.

**Comment by randomstuff** [comment]
This fixes the CSRF. However, you should probably avoid using a `GET` for this because this is a safe method. Your browser is allowed to prefetch them.
